max_width = 110
indent_style = "Block"
reorder_imports = true
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"
error_on_line_overflow = true
empty_item_single_line = false
enum_discrim_align_threshold = 30
struct_field_align_threshold = 30
fn_single_line = true
where_single_line = false
force_explicit_abi = true
format_strings = false
imports_indent = "Block"
imports_layout = "Mixed"
match_block_trailing_comma = true
merge_derives = true
force_multiline_blocks = false
newline_style = "Unix"
normalize_comments = false
remove_nested_parens = true
reorder_modules = true
reorder_impl_items = true
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_lit_single_line = false
tab_spaces = 2
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = false
use_try_shorthand = true
wrap_comments = false
match_arm_blocks = true
overflow_delimited_expr = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
color = "Always"
