name: "Versioning"
description: "Generate Semantic Version"
inputs:
  artifact:
    description: "name of the application"
    required: true
    default: "0.0.0"
outputs:
  version:
    description: "the generated version"
    value: ${{ steps.generate-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Generate Version
      id: generate-version
      run: echo "version=0.0.1" >> $GITHUB_OUTPUT
      shell: bash
